#!/usr/bin/env bash

function _cmake {
  CC=clang CXX=clang++ cmake $@
}

function _shdc {
  ./vendors/fips-deploy/sokol-tools/osx-xcode-debug/sokol-shdc \
  --input src/shaders/$1.glsl \
  --output include/maker/shaders/$1.glsl.h \
  --slang glsl430:hlsl5:metal_macos \
  --format sokol
}

function _cmake_generate {
  _cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
  -S . -B build \
  --log-level=DEBUG $@
}

function _cmake_build {
  _cmake --build build $@ &&\
  rm ./compile_commands.json &&\
  ln -s ./build/compile_commands.json
}

function install {
  : "Setup cmake project and sokol-tools"
  git submodule update --init --recursive &&\
  install:tools
}

function install:tools {
  : "Install sokol-tools"
  cd vendors/sokol-tools &&\
  ./fips build
}

function build {
  : "Build"
 # _shdc quad &&\
 _cmake_generate -DMAKER_APP=ON -DMAKER_TESTS=OFF &&\
 _cmake_build $@
}

function run {
  : "Build and run"
  build $@ && ./build/maker
}

function test {
  OPTS="--verbose"
  if [ -n "$1" ]; then
    OPTS="$OPTS -R ^test_$1$"
  fi
  _cmake_generate -DMAKER_APP=OFF -DMAKER_TESTS=ON &&\
  _cmake_build &&\
  cd ./build/tests &&\
  ctest $OPTS
}

function help {
  : "Auto-generate list of tasks, including documentation in the form of these noop statements"
  compgen -A function | grep -v "^_" | while read -r name; do
    paste <(printf '%s' "$name") <(type "$name" | sed -nEe 's/^[[:space:]]*: ?"(.*)";/\1/p')
  done
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
