#!/usr/bin/env bash

function _cmake {
  CC=clang CXX=clang++ cmake $@
}

function _shdc {
  ./vendors/fips-deploy/sokol-tools/osx-xcode-debug/sokol-shdc $@
}

function install {
  : "Setup cmake project and sokol-tools"
  git submodule update --init --recursive
  _cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -S . -B build --log-level=DEBUG $@
  rm ./compile_commands.json
  ln -s ./build/compile_commands.json ./
  install:tools
}

function install:tools {
  : "Install sokol-tools"
  cd vendors/sokol-tools
  ./fips build
}

function build {
  : "Build"
 _shdc --input src/quad.glsl --output src/quad.glsl.h --slang glsl430:hlsl5:metal_macos 
 _cmake --build build $@
}

function run {
  : "Build and run"
  build $@ && ./build/maker
}

function test {
  cd ./build/tests
  ctest
}

function help {
  : "Auto-generate list of tasks, including documentation in the form of these noop statements"
  compgen -A function | grep -v "^_" | while read -r name; do
    paste <(printf '%s' "$name") <(type "$name" | sed -nEe 's/^[[:space:]]*: ?"(.*)";/\1/p')
  done
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
